version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Taipei"
    groups:
      swift:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Taipei"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
